# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0004_auto_20160615_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
    ]
